/**
 * Consolidated edge-route dispatcher.
 *
 * Generated by a migration script (see MERIDIAN_FREE_TIER_PATCH.md) to fit
 * Vercel's Hobby-plan 12-serverless-function cap. Every route below used to be
 * its own physical Vercel function under api/; the implementations are
 * unchanged and now live under server/routes/, imported here and dispatched
 * by pathname. vercel.json rewrites every /api/* path (other than the 3
 * Node-runtime routes, which stay as their own functions) to this file.
 *
 * Each handler already parses everything it needs (method, path, query,
 * headers, body) directly from the standard Request object, so dispatching
 * here is a pure pass-through: no request rewriting, no framework magic.
 */

export const config = { runtime: 'edge' };

import h0 from '../server/routes/discord/oauth/callback';
import h1 from '../server/routes/discord/oauth/start';
import h2 from '../server/routes/slack/oauth/callback';
import h3 from '../server/routes/slack/oauth/start';
import h4 from '../server/routes/supply-chain/v1/multi-sector-cost-shock';
import h5 from '../server/routes/supply-chain/v1/country-products';
import h6 from '../server/routes/scenario/v1/templates';
import h7 from '../server/routes/scenario/v1/run';
import h8 from '../server/routes/scenario/v1/status';
import h9 from '../server/routes/oauth/register';
import h10 from '../server/routes/oauth/authorize-pro';
import h11 from '../server/routes/oauth/authorize';
import h12 from '../server/routes/oauth/token';
import h13 from '../server/routes/skills/fetch-agentskills';
import h14 from '../server/routes/user/mcp-revoke';
import h15 from '../server/routes/user/mcp-quota';
import h16 from '../server/routes/supply-chain/hormuz-tracker';
import h17 from '../server/routes/me/entitlement';
import h18 from '../server/routes/brief/share-url';
import h19 from '../server/routes/youtube/live';
import h20 from '../server/routes/youtube/embed';
import h21 from '../server/routes/referral/me';
import h22 from '../server/routes/internal/china-exchange-egress';
import h23 from '../server/routes/internal/mcp-grant-mint';
import h24 from '../server/routes/internal/mcp-grant-context';
import h25 from '../server/routes/internal/brief-why-matters';
import h26 from '../server/routes/security/report';
import h27 from '../server/routes/symbol-search';
import h28 from '../server/routes/polymarket';
import h29 from '../server/routes/mcp-proxy';
import h30 from '../server/routes/mcp';
import h31 from '../server/routes/seed-health';
import h32 from '../server/routes/health';
import h33 from '../server/routes/docs-mcp';
import h34 from '../server/routes/telegram-feed';
import h35 from '../server/routes/oauth-protected-resource';
import h36 from '../server/routes/invalidate-user-api-key-cache';
import h37 from '../server/routes/product-catalog';
import h38 from '../server/routes/widget-agent';
import h39 from '../server/routes/opensky';
import h40 from '../server/routes/analytics-health';
import h41 from '../server/routes/bootstrap';
import h42 from '../server/routes/ask';
import h43 from '../server/routes/agent-auth';
import h44 from '../server/routes/wm-session';
import h45 from '../server/routes/user-prefs';
import h46 from '../server/routes/cache-purge';
import h47 from '../server/routes/fwdstart';
import h48 from '../server/routes/geo';
import h49 from '../server/routes/create-checkout';
import h50 from '../server/routes/notify';
import h51 from '../server/routes/http-message-signatures-directory';
import h52 from '../server/routes/rss-proxy';
import h53 from '../server/routes/chat-analyst';
import h54 from '../server/routes/gpsjam';
import h55 from '../server/routes/download';
import h56 from '../server/routes/customer-portal';
import h57 from '../server/routes/latest-brief';
import h58 from '../server/routes/oref-alerts';
import h59 from '../server/routes/reverse-geocode';
import h60 from '../server/routes/seed-contract-probe';
import h61 from '../server/routes/oauth-authorization-server';
import h62 from '../server/routes/a2a';
import h63 from '../server/routes/version';
import h64 from '../server/routes/notification-channels';
import h65 from '../server/routes/not-found';
import h66 from '../server/routes/correlation-runtime-mode';
import h67 from '../server/routes/v2/shipping/webhooks/[subscriberId]';
import h68 from '../server/routes/aviation/v1/[rpc]';
import h69 from '../server/routes/infrastructure/v1/[rpc]';
import h70 from '../server/routes/economic/v1/[rpc]';
import h71 from '../server/routes/conflict/v1/[rpc]';
import h72 from '../server/routes/wildfire/v1/[rpc]';
import h73 from '../server/routes/research/v1/[rpc]';
import h74 from '../server/routes/sanctions/v1/[rpc]';
import h75 from '../server/routes/natural/v1/[rpc]';
import h76 from '../server/routes/supply-chain/v1/[rpc]';
import h77 from '../server/routes/prediction/v1/[rpc]';
import h78 from '../server/routes/giving/v1/[rpc]';
import h79 from '../server/routes/intelligence/v1/[rpc]';
import h80 from '../server/routes/displacement/v1/[rpc]';
import h81 from '../server/routes/v2/shipping/[rpc]';
import h82 from '../server/routes/scenario/v1/[rpc]';
import h83 from '../server/routes/consumer-prices/v1/[rpc]';
import h84 from '../server/routes/seismology/v1/[rpc]';
import h85 from '../server/routes/leads/v1/[rpc]';
import h86 from '../server/routes/brief/public/[hash]';
import h87 from '../server/routes/military/v1/[rpc]';
import h88 from '../server/routes/maritime/v1/[rpc]';
import h89 from '../server/routes/forecast/v1/[rpc]';
import h90 from '../server/routes/news/v1/[rpc]';
import h91 from '../server/routes/webcam/v1/[rpc]';
import h92 from '../server/routes/imagery/v1/[rpc]';
import h93 from '../server/routes/health/v1/[rpc]';
import h94 from '../server/routes/unrest/v1/[rpc]';
import h95 from '../server/routes/trade/v1/[rpc]';
import h96 from '../server/routes/radiation/v1/[rpc]';
import h97 from '../server/routes/climate/v1/[rpc]';
import h98 from '../server/routes/cyber/v1/[rpc]';
import h99 from '../server/routes/positive-events/v1/[rpc]';
import h100 from '../server/routes/thermal/v1/[rpc]';
import h101 from '../server/routes/resilience/v1/[rpc]';
import h102 from '../server/routes/batch/v1/[rpc]';
import h103 from '../server/routes/market/v1/[rpc]';
import h104 from '../server/routes/v2/shipping/webhooks/[subscriberId]/[action]';
import h105 from '../server/routes/brief/[userId]/[issueDate]';
import h106 from '../server/routes/brief/carousel/[userId]/[issueDate]/[page]';
import h107 from '../server/routes/[...notfound]';

type Handler = (req: Request, ctx: { waitUntil: (p: Promise<unknown>) => void }) => Response | Promise<Response>;

interface RouteEntry {
  segments: string[]; // literal segments, or '*'/'**' markers
  types: ('static' | 'dynamic' | 'catchall')[];
  handler: Handler;
}

const ROUTES: RouteEntry[] = [
  { segments: ["discord", "oauth", "callback"], types: ["static", "static", "static"], handler: h0 as Handler },
  { segments: ["discord", "oauth", "start"], types: ["static", "static", "static"], handler: h1 as Handler },
  { segments: ["slack", "oauth", "callback"], types: ["static", "static", "static"], handler: h2 as Handler },
  { segments: ["slack", "oauth", "start"], types: ["static", "static", "static"], handler: h3 as Handler },
  { segments: ["supply-chain", "v1", "multi-sector-cost-shock"], types: ["static", "static", "static"], handler: h4 as Handler },
  { segments: ["supply-chain", "v1", "country-products"], types: ["static", "static", "static"], handler: h5 as Handler },
  { segments: ["scenario", "v1", "templates"], types: ["static", "static", "static"], handler: h6 as Handler },
  { segments: ["scenario", "v1", "run"], types: ["static", "static", "static"], handler: h7 as Handler },
  { segments: ["scenario", "v1", "status"], types: ["static", "static", "static"], handler: h8 as Handler },
  { segments: ["oauth", "register"], types: ["static", "static"], handler: h9 as Handler },
  { segments: ["oauth", "authorize-pro"], types: ["static", "static"], handler: h10 as Handler },
  { segments: ["oauth", "authorize"], types: ["static", "static"], handler: h11 as Handler },
  { segments: ["oauth", "token"], types: ["static", "static"], handler: h12 as Handler },
  { segments: ["skills", "fetch-agentskills"], types: ["static", "static"], handler: h13 as Handler },
  { segments: ["user", "mcp-revoke"], types: ["static", "static"], handler: h14 as Handler },
  { segments: ["user", "mcp-quota"], types: ["static", "static"], handler: h15 as Handler },
  { segments: ["supply-chain", "hormuz-tracker"], types: ["static", "static"], handler: h16 as Handler },
  { segments: ["me", "entitlement"], types: ["static", "static"], handler: h17 as Handler },
  { segments: ["brief", "share-url"], types: ["static", "static"], handler: h18 as Handler },
  { segments: ["youtube", "live"], types: ["static", "static"], handler: h19 as Handler },
  { segments: ["youtube", "embed"], types: ["static", "static"], handler: h20 as Handler },
  { segments: ["referral", "me"], types: ["static", "static"], handler: h21 as Handler },
  { segments: ["internal", "china-exchange-egress"], types: ["static", "static"], handler: h22 as Handler },
  { segments: ["internal", "mcp-grant-mint"], types: ["static", "static"], handler: h23 as Handler },
  { segments: ["internal", "mcp-grant-context"], types: ["static", "static"], handler: h24 as Handler },
  { segments: ["internal", "brief-why-matters"], types: ["static", "static"], handler: h25 as Handler },
  { segments: ["security", "report"], types: ["static", "static"], handler: h26 as Handler },
  { segments: ["symbol-search"], types: ["static"], handler: h27 as Handler },
  { segments: ["polymarket"], types: ["static"], handler: h28 as Handler },
  { segments: ["mcp-proxy"], types: ["static"], handler: h29 as Handler },
  { segments: ["mcp"], types: ["static"], handler: h30 as Handler },
  { segments: ["seed-health"], types: ["static"], handler: h31 as Handler },
  { segments: ["health"], types: ["static"], handler: h32 as Handler },
  { segments: ["docs-mcp"], types: ["static"], handler: h33 as Handler },
  { segments: ["telegram-feed"], types: ["static"], handler: h34 as Handler },
  { segments: ["oauth-protected-resource"], types: ["static"], handler: h35 as Handler },
  { segments: ["invalidate-user-api-key-cache"], types: ["static"], handler: h36 as Handler },
  { segments: ["product-catalog"], types: ["static"], handler: h37 as Handler },
  { segments: ["widget-agent"], types: ["static"], handler: h38 as Handler },
  { segments: ["opensky"], types: ["static"], handler: h39 as Handler },
  { segments: ["analytics-health"], types: ["static"], handler: h40 as Handler },
  { segments: ["bootstrap"], types: ["static"], handler: h41 as Handler },
  { segments: ["ask"], types: ["static"], handler: h42 as Handler },
  { segments: ["agent-auth"], types: ["static"], handler: h43 as Handler },
  { segments: ["wm-session"], types: ["static"], handler: h44 as Handler },
  { segments: ["user-prefs"], types: ["static"], handler: h45 as Handler },
  { segments: ["cache-purge"], types: ["static"], handler: h46 as Handler },
  { segments: ["fwdstart"], types: ["static"], handler: h47 as Handler },
  { segments: ["geo"], types: ["static"], handler: h48 as Handler },
  { segments: ["create-checkout"], types: ["static"], handler: h49 as Handler },
  { segments: ["notify"], types: ["static"], handler: h50 as Handler },
  { segments: ["http-message-signatures-directory"], types: ["static"], handler: h51 as Handler },
  { segments: ["rss-proxy"], types: ["static"], handler: h52 as Handler },
  { segments: ["chat-analyst"], types: ["static"], handler: h53 as Handler },
  { segments: ["gpsjam"], types: ["static"], handler: h54 as Handler },
  { segments: ["download"], types: ["static"], handler: h55 as Handler },
  { segments: ["customer-portal"], types: ["static"], handler: h56 as Handler },
  { segments: ["latest-brief"], types: ["static"], handler: h57 as Handler },
  { segments: ["oref-alerts"], types: ["static"], handler: h58 as Handler },
  { segments: ["reverse-geocode"], types: ["static"], handler: h59 as Handler },
  { segments: ["seed-contract-probe"], types: ["static"], handler: h60 as Handler },
  { segments: ["oauth-authorization-server"], types: ["static"], handler: h61 as Handler },
  { segments: ["a2a"], types: ["static"], handler: h62 as Handler },
  { segments: ["version"], types: ["static"], handler: h63 as Handler },
  { segments: ["notification-channels"], types: ["static"], handler: h64 as Handler },
  { segments: ["not-found"], types: ["static"], handler: h65 as Handler },
  { segments: ["correlation-runtime-mode"], types: ["static"], handler: h66 as Handler },
  { segments: ["v2", "shipping", "webhooks", "subscriberId"], types: ["static", "static", "static", "dynamic"], handler: h67 as Handler },
  { segments: ["aviation", "v1", "rpc"], types: ["static", "static", "dynamic"], handler: h68 as Handler },
  { segments: ["infrastructure", "v1", "rpc"], types: ["static", "static", "dynamic"], handler: h69 as Handler },
  { segments: ["economic", "v1", "rpc"], types: ["static", "static", "dynamic"], handler: h70 as Handler },
  { segments: ["conflict", "v1", "rpc"], types: ["static", "static", "dynamic"], handler: h71 as Handler },
  { segments: ["wildfire", "v1", "rpc"], types: ["static", "static", "dynamic"], handler: h72 as Handler },
  { segments: ["research", "v1", "rpc"], types: ["static", "static", "dynamic"], handler: h73 as Handler },
  { segments: ["sanctions", "v1", "rpc"], types: ["static", "static", "dynamic"], handler: h74 as Handler },
  { segments: ["natural", "v1", "rpc"], types: ["static", "static", "dynamic"], handler: h75 as Handler },
  { segments: ["supply-chain", "v1", "rpc"], types: ["static", "static", "dynamic"], handler: h76 as Handler },
  { segments: ["prediction", "v1", "rpc"], types: ["static", "static", "dynamic"], handler: h77 as Handler },
  { segments: ["giving", "v1", "rpc"], types: ["static", "static", "dynamic"], handler: h78 as Handler },
  { segments: ["intelligence", "v1", "rpc"], types: ["static", "static", "dynamic"], handler: h79 as Handler },
  { segments: ["displacement", "v1", "rpc"], types: ["static", "static", "dynamic"], handler: h80 as Handler },
  { segments: ["v2", "shipping", "rpc"], types: ["static", "static", "dynamic"], handler: h81 as Handler },
  { segments: ["scenario", "v1", "rpc"], types: ["static", "static", "dynamic"], handler: h82 as Handler },
  { segments: ["consumer-prices", "v1", "rpc"], types: ["static", "static", "dynamic"], handler: h83 as Handler },
  { segments: ["seismology", "v1", "rpc"], types: ["static", "static", "dynamic"], handler: h84 as Handler },
  { segments: ["leads", "v1", "rpc"], types: ["static", "static", "dynamic"], handler: h85 as Handler },
  { segments: ["brief", "public", "hash"], types: ["static", "static", "dynamic"], handler: h86 as Handler },
  { segments: ["military", "v1", "rpc"], types: ["static", "static", "dynamic"], handler: h87 as Handler },
  { segments: ["maritime", "v1", "rpc"], types: ["static", "static", "dynamic"], handler: h88 as Handler },
  { segments: ["forecast", "v1", "rpc"], types: ["static", "static", "dynamic"], handler: h89 as Handler },
  { segments: ["news", "v1", "rpc"], types: ["static", "static", "dynamic"], handler: h90 as Handler },
  { segments: ["webcam", "v1", "rpc"], types: ["static", "static", "dynamic"], handler: h91 as Handler },
  { segments: ["imagery", "v1", "rpc"], types: ["static", "static", "dynamic"], handler: h92 as Handler },
  { segments: ["health", "v1", "rpc"], types: ["static", "static", "dynamic"], handler: h93 as Handler },
  { segments: ["unrest", "v1", "rpc"], types: ["static", "static", "dynamic"], handler: h94 as Handler },
  { segments: ["trade", "v1", "rpc"], types: ["static", "static", "dynamic"], handler: h95 as Handler },
  { segments: ["radiation", "v1", "rpc"], types: ["static", "static", "dynamic"], handler: h96 as Handler },
  { segments: ["climate", "v1", "rpc"], types: ["static", "static", "dynamic"], handler: h97 as Handler },
  { segments: ["cyber", "v1", "rpc"], types: ["static", "static", "dynamic"], handler: h98 as Handler },
  { segments: ["positive-events", "v1", "rpc"], types: ["static", "static", "dynamic"], handler: h99 as Handler },
  { segments: ["thermal", "v1", "rpc"], types: ["static", "static", "dynamic"], handler: h100 as Handler },
  { segments: ["resilience", "v1", "rpc"], types: ["static", "static", "dynamic"], handler: h101 as Handler },
  { segments: ["batch", "v1", "rpc"], types: ["static", "static", "dynamic"], handler: h102 as Handler },
  { segments: ["market", "v1", "rpc"], types: ["static", "static", "dynamic"], handler: h103 as Handler },
  { segments: ["v2", "shipping", "webhooks", "subscriberId", "action"], types: ["static", "static", "static", "dynamic", "dynamic"], handler: h104 as Handler },
  { segments: ["brief", "userId", "issueDate"], types: ["static", "dynamic", "dynamic"], handler: h105 as Handler },
  { segments: ["brief", "carousel", "userId", "issueDate", "page"], types: ["static", "static", "dynamic", "dynamic", "dynamic"], handler: h106 as Handler },
  { segments: ["notfound"], types: ["catchall"], handler: h107 as Handler },
];

function matchRoute(pathname: string): Handler | null {
  // Strip leading /api/ and split into segments.
  const trimmed = pathname.replace(/^\/api\/?/, '');
  const parts = trimmed.length ? trimmed.split('/') : [];

  for (const route of ROUTES) {
    const { segments, types } = route;
    const hasCatchall = types[types.length - 1] === 'catchall';

    if (!hasCatchall) {
      if (parts.length !== segments.length) continue;
    } else {
      // catch-all requires at least the segments before it to be present
      if (parts.length < segments.length - 1) continue;
    }

    let ok = true;
    for (let i = 0; i < segments.length; i++) {
      const type = types[i];
      if (type === 'static') {
        if (parts[i] !== segments[i]) { ok = false; break; }
      }
      // dynamic and catchall segments match anything (including catchall
      // matching zero or more remaining parts, already length-checked above)
    }
    if (ok) return route.handler;
  }
  return null;
}

export default async function handler(
  req: Request,
  ctx: { waitUntil: (p: Promise<unknown>) => void },
): Promise<Response> {
  const url = new URL(req.url);
  const routeHandler = matchRoute(url.pathname);
  if (!routeHandler) {
    return new Response(JSON.stringify({ error: 'Not found' }), {
      status: 404,
      headers: { 'Content-Type': 'application/json' },
    });
  }
  return routeHandler(req, ctx);
}
